# add travi yml file
language: java
dist: trusty
sudo: required

before_install:
- sudo apt-get install software-properties-common -y
- sudo apt-add-repository ppa:brightbox/ruby-ng -y
- sudo apt-get update
- sudo apt-get install build-essential ruby2.2 ruby2.2-dev zlib1g-dev liblzma-dev -y
- sudo gem install bundler
- sudo gem install deb-s3

deploy:
  provider: gcs
  access_key_id: "GOOGJZTKC2LBNVEGLFFW"
  secret_access_key: "FSEwvHea1f7ja+MQbY8G8A1HobS+mLSTVfzsTj1U"
  bucket: "test-travis-123"
  skip_cleanup: true
