# add travi yml file
language: java
dist: trusty
sudo: required


script:
- ./gradlew clean packDeb

deploy:
  provider: gcs
  access_key_id: $gcp_access
  secret_access_key: $gcp_secret
  bucket: "test-travis-123"
  skip_cleanup: true
